sudo: required
services: 
  - docker

before-install:
  - docker build -t tkathuria/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true tkathuria/docker-react npm run test -- --coverage